// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0M2TBvAccaF5QDV3o_nO5EvsA-Gwxp9g',
    appId: '1:121498991170:web:28d8b95ba1ddd929064bdb',
    messagingSenderId: '121498991170',
    projectId: 'safe-pink-9a8e2',
    authDomain: 'safe-pink-9a8e2.firebaseapp.com',
    storageBucket: 'safe-pink-9a8e2.appspot.com',
    measurementId: 'G-S9PH6525PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYDrBeH9hBZOgUMbuyV2SWYp2XWye_o-g',
    appId: '1:121498991170:android:aa71e8aa8b8cb38c064bdb',
    messagingSenderId: '121498991170',
    projectId: 'safe-pink-9a8e2',
    storageBucket: 'safe-pink-9a8e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHdZgtVEcOoJvsn6OpSDOZDK5uKWEXEhc',
    appId: '1:121498991170:ios:84fd2625c209a125064bdb',
    messagingSenderId: '121498991170',
    projectId: 'safe-pink-9a8e2',
    storageBucket: 'safe-pink-9a8e2.appspot.com',
    iosBundleId: 'com.example.safePink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHdZgtVEcOoJvsn6OpSDOZDK5uKWEXEhc',
    appId: '1:121498991170:ios:84fd2625c209a125064bdb',
    messagingSenderId: '121498991170',
    projectId: 'safe-pink-9a8e2',
    storageBucket: 'safe-pink-9a8e2.appspot.com',
    iosBundleId: 'com.example.safePink',
  );
}
